package by.epam.lesson20.entity;

public enum RentShopTagName {
	RENTSHOP, BIKE_PRODUCTS, PRODUCT, PRODUCTNAME, BASEPRICE, NOTE, MANUFACTURINGYEAR, WEARRATE, STATUS, NAVIGATOR_PRODUCTS, ACCESSORIES
}
